version: '3'

services:
  database:
    image: 'postgres:15-alpine'
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: ./app
    container_name: app
    ports:
      - 3000:3000
    environment:
      - DB_SERVER=database
    depends_on: 
      - database

  
